name = "notion-coding-web"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Opsional: pakai Workers AI Cloudflare buat chat (gantinya OpenAI eksternal)
# [ai]
# binding = "AI"

# Wajib buat simpan riwayat chat di server (bikin namespace-nya dulu)
[[kv_namespaces]]
binding = "CHAT"
id = "b591811336a04f63b21512d35edf4e67"
