function __clientMain(){
var BT=String.fromCharCode(96);var FENCE=BT+BT+BT;
function $(i){return document.getElementById(i)}
function esc(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function el(t,c,h){var e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e}
function toast(m,err){var t=$("toast");t.textContent=m;t.className="show"+(err?" err":"");clearTimeout(window.__tt);window.__tt=setTimeout(function(){t.className=""},err?4000:2200)}
var EXT={javascript:"js",typescript:"ts",python:"py",java:"java",c:"c","c++":"cpp","c#":"cs",go:"go",rust:"rs",ruby:"rb",php:"php",html:"html",css:"css",json:"json",yaml:"yml",bash:"sh",shell:"sh",sql:"sql",markdown:"md",kotlin:"kt",swift:"swift",dart:"dart"};
var LANGS=["plain text","javascript","typescript","python","java","c","c++","c#","go","rust","ruby","php","html","css","json","yaml","bash","shell","sql","markdown","kotlin","swift","dart"];
var TEXTEXT=["js","ts","py","java","c","cpp","cs","go","rs","rb","php","html","css","json","yml","yaml","sh","sql","md","txt","kt","swift","dart","xml","vue","jsx","tsx","toml","ini","cfg"];
var IMGEXT=["png","jpg","jpeg","gif","webp","bmp","svg"];
var state={pages:[],current:null,title:"",blocks:[],chat:[],chatId:null,memory:[],context:[]};
var editing=-1;var pending=[];var __sessions=[];
function rtP(rt){return (rt||[]).map(function(t){return t.plain_text||""}).join("")}
function rt(arr){return (arr||[]).map(function(t){var x=esc(t.plain_text||"");var a=t.annotations||{};if(a.code)x="<code>"+x+"</code>";if(a.bold)x="<b>"+x+"</b>";if(a.italic)x="<i>"+x+"</i>";if(a.strikethrough)x="<s>"+x+"</s>";if(t.href)x='<a href="'+esc(t.href)+'" target="_blank">'+x+"</a>";return x}).join("")}
function accParam(){var v=$("acc").value||"0";var tb=$("turbo")&&$("turbo").checked?"&turbo=1":"";return "&acc="+encodeURIComponent(v)+tb}
async function loadAccounts(){try{var r=await fetch("/api/accounts");var d=await r.json();var sel=$("acc");sel.innerHTML="";var a=d.accounts||[];if(a.length>1){var oa=el("option","","🔀 Auto (failover)");oa.value="auto";sel.appendChild(oa)}a.forEach(function(x){var o=el("option","",esc(x.name));o.value=x.index;sel.appendChild(o)});if(a.length>1){sel.value="auto";$("turbowrap").style.display="flex"}else{$("turbowrap").style.display="none"}}catch(e){toast("Gagal load akun",true)}}
async function loadModels(){try{var r=await fetch("/api/models");var d=await r.json();var dl=$("modellist");dl.innerHTML="";(d.models||[]).forEach(function(m){var o=el("option");o.value=m;dl.appendChild(o)})}catch(e){}}
async function doSearch(){var q=$("search").value;try{var r=await fetch("/api/search?q="+encodeURIComponent(q)+accParam());var d=await r.json();if(d.needsToken){state.pages=[];renderList(true);return}if(d.error){toast(d.error,true);state.pages=[]}else state.pages=d.results||[];renderList()}catch(e){toast("Gagal search",true)}}
function renderList(needsToken){var box=$("plist");box.innerHTML="";if(needsToken){box.innerHTML='<p class="muted" style="font-size:12px">Tambahin Notion token di Pengaturan (ikon gear) buat cari &amp; buka halaman. Chat &amp; GitHub tetap jalan tanpa token.</p>';return}if(!state.pages.length){box.innerHTML='<p class="muted" style="font-size:12px">Nggak ada hasil.</p>';return}state.pages.forEach(function(p){var it=el("div","pitem"+(state.current===p.id?" active":""),esc(p.title));it.onclick=function(){openPage(p.id)};box.appendChild(it)})}
async function openPage(id){state.current=id;renderList();$("page").innerHTML='<p class="muted">Memuat...</p>';try{var r=await fetch("/api/page?id="+encodeURIComponent(id)+accParam());var d=await r.json();if(d.error){$("page").innerHTML='<p class="muted">'+esc(d.error)+"</p>";toast(d.error,true);return}state.title=d.title;state.blocks=d.blocks||[];renderPage();updatePinBtn();renderCtxInfo();if(window.innerWidth>900)document.body.classList.add("shownotion")}catch(e){toast("Gagal buka halaman",true)}}
function renderPage(){var box=$("page");box.innerHTML='<div class="title">'+esc(state.title)+"</div>";state.blocks.forEach(function(b){var h=renderBlock(b);if(h){var w=el("div");w.innerHTML=h;while(w.firstChild)box.appendChild(w.firstChild)}});try{box.querySelectorAll("pre code").forEach(function(c){hljs.highlightElement(c)})}catch(e){}}
function renderBlock(b){var t=b.type;var v=b[t]||{};var kids=b.children?b.children.map(renderBlock).join(""):"";if(t==="code")return codeCard(b);if(t==="image"){var src=v.type==="external"?v.external.url:(v.file?v.file.url:"");return '<div class="block"><img src="'+esc(src)+'" style="max-width:100%;border-radius:8px"/></div>'}if(t==="divider")return "<hr/>";var txt=rt(v.rich_text);if(t==="heading_1")return '<div class="block"><h2>'+txt+"</h2></div>"+kids;if(t==="heading_2"||t==="heading_3")return '<div class="block"><h3>'+txt+"</h3></div>"+kids;if(t==="bulleted_list_item"||t==="numbered_list_item")return '<div class="block">\u2022 '+txt+"</div>"+kids;if(t==="to_do")return '<div class="block">'+(v.checked?"\u2611":"\u2610")+" "+txt+"</div>"+kids;if(t==="quote")return "<blockquote>"+txt+"</blockquote>"+kids;if(t==="callout")return '<div class="callout"><div>'+((v.icon&&v.icon.emoji)||"\ud83d\udca1")+'</div><div>'+txt+"</div></div>"+kids;if(t==="toggle")return "<details><summary>"+txt+"</summary>"+kids+"</details>";if(t==="child_page")return '<div class="block">\ud83d\udcc4 '+esc(v.title||"")+"</div>";if(txt)return '<div class="block">'+txt+"</div>"+kids;return kids}
function codeCard(b){var v=b.code||{};var txt=rtP(v.rich_text);var lang=v.language||"plain text";var card=el("div","codecard");card.setAttribute("data-block",b.id);var head=el("div","codehead");var ls=el("select");LANGS.forEach(function(l){var o=el("option","",l);o.value=l;if(l===lang)o.selected=true;ls.appendChild(o)});head.appendChild(ls);var sp=el("span","sp");head.appendChild(sp);var eb=el("button","btn","\u270f\ufe0f");var cb=el("button","btn","\ud83d\udccb");head.appendChild(eb);head.appendChild(cb);var pre=el("pre");var code=el("code","language-"+lang);code.textContent=txt;pre.appendChild(code);card.appendChild(head);card.appendChild(pre);var editingNow=false;eb.onclick=function(){if(!editingNow){var ta=el("textarea");ta.value=code.textContent;card.replaceChild(ta,pre);eb.textContent="\ud83d\udcbe";editingNow=true}else{var ta=card.querySelector("textarea");var nt=ta.value;fetch("/api/block",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:b.id,text:nt,language:ls.value,acc:$("acc").value})}).then(function(r){return r.json()}).then(function(d){if(d.error)toast(d.error,true);else toast("Tersimpan ke Notion")}).catch(function(){toast("Gagal simpan",true)});var np=el("pre");var nc=el("code","language-"+ls.value);nc.textContent=nt;np.appendChild(nc);card.replaceChild(np,ta);pre=np;code=nc;try{hljs.highlightElement(nc)}catch(e){}eb.textContent="\u270f\ufe0f";editingNow=false}};cb.onclick=function(){navigator.clipboard.writeText(code.textContent);toast("Disalin")};try{hljs.highlightElement(code)}catch(e){}var tmp=el("div");tmp.appendChild(card);return tmp.innerHTML}
function collectCode(){var out=[];function walk(arr){(arr||[]).forEach(function(b){if(b.type==="code"){out.push({language:b.code.language||"plain text",text:rtP(b.code.rich_text),path:""})}if(b.children)walk(b.children)})}walk(state.blocks);return out}
function extOf(lang){return EXT[lang]||"txt"}
function zipName(c,i){if(c.path)return c.path.replace(/^\/+/,"");return "file_"+(i+1)+"."+extOf(c.language)}
function addToZip(zip,list){var seen={};list.forEach(function(c,i){var fn=zipName(c,i);seen[fn]=(seen[fn]||0)+1;if(seen[fn]>1)fn=(i+1)+"_"+fn;zip.file(fn,c.text)})}
function downloadFile(name,blob){var a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
async function exportZip(){var codes=collectCode();if(!codes.length){toast("Nggak ada kode di halaman ini",true);return}var zip=new JSZip();addToZip(zip,codes);var blob=await zip.generateAsync({type:"blob"});downloadFile((state.title||"notion").replace(/[^a-z0-9]/gi,"_")+".zip",blob)}
async function addCode(){if(!state.current){toast("Buka halaman dulu",true);return}var lang=prompt("Bahasa (mis. javascript):","javascript");if(lang==null)return;var text=prompt("Isi kode:","");if(text==null)return;try{var r=await fetch("/api/append",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pageId:state.current,text:text,language:lang,acc:$("acc").value})});var d=await r.json();if(d.error){toast(d.error,true)}else{toast("Code block ditambahkan");openPage(state.current)}}catch(e){toast("Gagal nambah",true)}}
function addContext(){if(!state.current){toast("Buka halaman dulu",true);return}if(state.context.some(function(x){return x.id===state.current})){toast("Sudah ada di konteks");return}state.context.push({id:state.current,title:state.title,codes:collectCode()});toast("Konteks + "+state.title);renderCtxInfo()}
function clearContext(){state.context=[];renderCtxInfo();toast("Konteks dikosongkan")}
function renderCtxInfo(){var n=state.context.length;var t=$("ctxinfo");if(n){t.textContent="("+n+" item \u00d7)";t.title="Klik buat kosongkan"}else{t.textContent=($("ctx").checked&&state.blocks.length)?"(halaman aktif)":"";t.title=""}}
function getPins(){try{return JSON.parse(localStorage.getItem("pins")||"[]")}catch(e){return[]}}
function setPins(p){localStorage.setItem("pins",JSON.stringify(p))}
function isPinned(id){return getPins().some(function(x){return x.id===id})}
function renderPins(){var box=$("pins");var pins=getPins();if(!pins.length){box.style.display="none";return}box.style.display="flex";box.innerHTML='<div class="muted" style="font-size:11px">📌 Pinned</div>';pins.forEach(function(p){var it=el("div","pitem",esc(p.title));it.onclick=function(){openPage(p.id)};box.appendChild(it)})}
function updatePinBtn(){$("pinbtn").textContent=isPinned(state.current)?"\ud83d\udccc Unpin":"\ud83d\udccc Pin"}
function togglePin(){if(!state.current)return;var pins=getPins();if(isPinned(state.current)){pins=pins.filter(function(x){return x.id!==state.current})}else{pins.push({id:state.current,title:state.title})}setPins(pins);renderPins();updatePinBtn()}
function findInPage(q){var box=$("page");box.querySelectorAll("mark.find").forEach(function(m){m.replaceWith(document.createTextNode(m.textContent))});box.normalize();if(!q)return;var walk=document.createTreeWalker(box,NodeFilter.SHOW_TEXT,null);var nodes=[];while(walk.nextNode())nodes.push(walk.currentNode);var ql=q.toLowerCase();nodes.forEach(function(n){if(n.parentNode&&n.parentNode.tagName==="CODE")return;var txt=n.nodeValue;var low=txt.toLowerCase();if(low.indexOf(ql)<0)return;var frag=document.createDocumentFragment();var i=0,idx;while((idx=low.indexOf(ql,i))>=0){frag.appendChild(document.createTextNode(txt.slice(i,idx)));var mk=el("mark","find",esc(txt.slice(idx,idx+q.length)));frag.appendChild(mk);i=idx+q.length}frag.appendChild(document.createTextNode(txt.slice(i)));n.parentNode.replaceChild(frag,n)})}
function applyTheme(){var t=localStorage.getItem("theme")||"dark";if(t==="light")document.body.classList.add("light");else document.body.classList.remove("light")}
function toggleTheme(){var light=document.body.classList.toggle("light");localStorage.setItem("theme",light?"light":"dark")}
function updateBackdrop(){var bd=$("backdrop");var mob=window.innerWidth<=900;var open=mob&&((!document.body.classList.contains("nohist"))||document.body.classList.contains("shownotion"));bd.style.display=open?"block":"none"}
function nearBottom(){var c=$("msgs");return (c.scrollHeight-c.scrollTop-c.clientHeight)<80}
function updateScrollBtn(){var b=$("scrollbtn");if(!b)return;b.style.display=nearBottom()?"none":"flex"}
function mdInline(s){s=s.replace(/\*\*([^*]+)\*\*/g,"<b>$1</b>").replace(/(^|[^*])\*([^*]+)\*/g,"$1<i>$2</i>").replace(/~~([^~]+)~~/g,"<s>$1</s>").replace(new RegExp(BT+"([^"+BT+"]+)"+BT,"g"),"<code>$1</code>").replace(/\[([^\]]+)\]\((https?:[^)]+)\)/g,'<a href="$2" target="_blank">$1</a>');return s}
function mdRender(text){var lines=String(text).split("\n");var out="";var i=0;while(i<lines.length){var ln=lines[i];if(ln.indexOf(FENCE)===0){var info=ln.slice(3).trim();var lang=info.split(" ")[0];var buf=[];i++;while(i<lines.length&&lines[i].indexOf(FENCE)!==0){buf.push(lines[i]);i++}i++;var __ch='<pre><code'+(lang?' class="language-'+esc(lang)+'"':"")+">"+esc(buf.join("\n"))+"</code></pre>";if(buf.length>14){out+='<div class="codewrap collapsed"><div class="codebar"><span class="cwlang">'+esc(lang||"code")+' ('+buf.length+' baris)</span><button type="button" class="codetoggle">Lebarkan</button></div>'+__ch+'</div>'}else{out+=__ch};continue}var h=ln.match(/^(#{1,4})\s+(.*)$/);if(h){var n=h[1].length;out+="<h"+n+">"+mdInline(esc(h[2]))+"</h"+n+">";i++;continue}var b=ln.match(/^[-*]\s+(.*)$/);if(b){var items=[];while(i<lines.length&&lines[i].match(/^[-*]\s+(.*)$/)){items.push(lines[i].replace(/^[-*]\s+/,""));i++}out+="<ul>"+items.map(function(x){return "<li>"+mdInline(esc(x))+"</li>"}).join("")+"</ul>";continue}var nm=ln.match(/^\d+\.\s+(.*)$/);if(nm){var its=[];while(i<lines.length&&lines[i].match(/^\d+\.\s+(.*)$/)){its.push(lines[i].replace(/^\d+\.\s+/,""));i++}out+="<ol>"+its.map(function(x){return "<li>"+mdInline(esc(x))+"</li>"}).join("")+"</ol>";continue}if(ln.trim()===""){out+="";i++;continue}out+="<p>"+mdInline(esc(ln))+"</p>";i++}return out}
function parseOpts(text){var lines=String(text).split("\n");var body=[];var opts=[];lines.forEach(function(l){if(l.indexOf("::OPTIONS::")===0){l.slice(11).split("|").forEach(function(o){var t=o.trim();if(t)opts.push(t)})}else body.push(l)});return{body:body.join("\n"),opts:opts}}
function stripMemory(text){var lines=String(text).split("\n");var body=[];lines.forEach(function(l){if(l.indexOf("::MEMORY::")!==0)body.push(l)});return{body:body.join("\n")}}
function collectMemoryFrom(text){var facts=[];String(text).split("\n").forEach(function(l){if(l.indexOf("::MEMORY::")===0){var f=l.slice(10).trim();if(f)facts.push(f)}});return facts}
async function loadMemory(){try{var r=await fetch("/api/memory");var d=await r.json();state.memory=d.facts||[]}catch(e){}}
async function saveMemory(){try{await fetch("/api/memory/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({facts:state.memory})})}catch(e){}}
function showMemory(){var nv=prompt("Memori AI (satu fakta per baris). Kosongkan buat hapus semua:",state.memory.join("\n"));if(nv==null)return;state.memory=nv.split("\n").map(function(x){return x.trim()}).filter(function(x){return x});saveMemory();toast("Memori disimpan")}
function extOfName(n){var p=String(n).split(".");return p.length>1?p.pop().toLowerCase():""}
function extFromPath(p){var e=extOfName(p);return e||"plain text"}
function isImgType(ext){return IMGEXT.indexOf(ext)>=0}
function readFileObj(file){return new Promise(function(res){var ext=extOfName(file.name);var reader=new FileReader();if(isImgType(ext)){reader.onload=function(){res({name:file.name,kind:"image",dataUrl:reader.result})};reader.readAsDataURL(file)}else if(TEXTEXT.indexOf(ext)>=0||file.size<200000){reader.onload=function(){res({name:file.name,kind:"text",text:reader.result})};reader.readAsText(file)}else{res({name:file.name,kind:"other"})}})}
async function handleZip(file){var zip=await JSZip.loadAsync(file);var files=[];var names=Object.keys(zip.files);for(var i=0;i<names.length;i++){var zf=zip.files[names[i]];if(zf.dir)continue;var ext=extOfName(names[i]);if(TEXTEXT.indexOf(ext)>=0){var txt=await zf.async("string");files.push({name:names[i],kind:"text",text:txt})}else{files.push({name:names[i],kind:"other"})}}return files}
async function addFiles(fl){for(var i=0;i<fl.length;i++){var f=fl[i];if(extOfName(f.name)==="zip"){try{var inner=await handleZip(f);pending=pending.concat(inner);toast("ZIP: "+inner.length+" file dimuat")}catch(e){toast("Gagal baca zip",true)}}else{var obj=await readFileObj(f);pending.push(obj)}}renderAttbar()}
function renderAttbar(){var box=$("attbar");box.innerHTML="";pending.forEach(function(f,i){var a=el("div","att");a.innerHTML=(f.kind==="image"?"\ud83d\uddbc\ufe0f ":"\ud83d\udcc4 ")+esc(f.name);var x=el("span","x"," \u2715");x.onclick=function(){pending.splice(i,1);renderAttbar()};a.appendChild(x);box.appendChild(a)})}
function filesHtml(files){var h="";var imgs=files.filter(function(f){return f.kind==="image"});var others=files.filter(function(f){return f.kind!=="image"});if(imgs.length){h+='<div class="thumbs">'+imgs.map(function(f){return '<img src="'+esc(f.dataUrl)+'" title="'+esc(f.name)+'"/>'}).join("")+"</div>"}others.forEach(function(f){h+='<div class="filechip">\ud83d\udcc4 '+esc(f.name)+"</div>"});return h}
function parseFence(info){info=String(info).trim();var sp=info.indexOf(" ");if(sp<0)return{language:info||"plain text",path:""};return{language:info.slice(0,sp)||"plain text",path:info.slice(sp+1).trim()}}
function collectCodeFromText(text){var out=[];var lines=String(text).split("\n");var i=0;while(i<lines.length){if(lines[i].indexOf(FENCE)===0){var meta=parseFence(lines[i].slice(3));var buf=[];i++;while(i<lines.length&&lines[i].indexOf(FENCE)!==0){buf.push(lines[i]);i++}i++;out.push({language:meta.language,path:meta.path,text:buf.join("\n")})}else i++}return out}
async function zipFromText(text,base){var codes=collectCodeFromText(text);if(!codes.length){toast("Nggak ada kode",true);return}var zip=new JSZip();addToZip(zip,codes);var blob=await zip.generateAsync({type:"blob"});downloadFile((base||"output")+".zip",blob)}
function isZipCmd(t){t=t.toLowerCase();return (t.indexOf("zip")>=0)&&(t.indexOf("semua")>=0||t.indexOf("all")>=0||t.indexOf("jadikan")>=0||t.indexOf("jadiin")>=0||t.indexOf("satu")>=0)}
async function zipAll(){var codes=collectCode();var fromChat=[];state.chat.forEach(function(m){if(m.role==="assistant")fromChat=fromChat.concat(collectCodeFromText(m.content))});var all=codes.concat(fromChat);if(!all.length){toast("Nggak ada kode buat di-zip",true);return}var zip=new JSZip();addToZip(zip,all);var blob=await zip.generateAsync({type:"blob"});downloadFile("semua-kode.zip",blob);toast("ZIP berisi "+all.length+" file")}
function pushMsg(role,content,files){state.chat.push({role:role,content:content,files:files||[]})}
function renderChat(){var c=$("msgs");c.innerHTML="";if(!state.chat.length){var emp=el("div","empty");emp.innerHTML='<div class="hello">Mau ngoding apa hari ini?</div><div>Tanya apa aja, lampirin file/foto/zip, atau buka halaman Notion di kanan.</div>';c.appendChild(emp);return}var th=el("div","thread");state.chat.forEach(function(m,i){var d=el("div","msg "+m.role);d.appendChild(el("div","avatar",m.role==="user"?"\ud83e\uddd1":"\ud83e\udd16"));var body=el("div","mbody");if(editing===i){var ta=el("textarea");ta.className="set";ta.value=m.content;ta.rows=4;body.appendChild(ta);var rw=el("div","row");rw.style.marginTop="6px";var sv=el("button","btn accent","Simpan & generate");var cn=el("button","btn","Batal");rw.appendChild(sv);rw.appendChild(cn);body.appendChild(rw);sv.onclick=function(){saveEdit(i,ta.value)};cn.onclick=function(){editing=-1;renderChat()};d.appendChild(body);th.appendChild(d);return}var pr=m.role==="assistant"?parseOpts(stripMemory(m.content).body):{body:m.content,opts:[]};var bub=el("div","bubble",mdRender(pr.body));body.appendChild(bub);try{bub.querySelectorAll("pre code").forEach(function(cb){hljs.highlightElement(cb)})}catch(e){}if(m.files&&m.files.length){var fh=el("div");fh.innerHTML=filesHtml(m.files);body.appendChild(fh)}if(pr.opts.length){var ob=el("div","opts");pr.opts.forEach(function(op){var chip=el("button","chip",esc(op));chip.onclick=function(){$("chatin").value=op;sendChat()};ob.appendChild(chip)});body.appendChild(ob)}var act=el("div","msgact");if(m.role==="user"){var eb=el("button","mini","\u270f\ufe0f Edit");eb.onclick=function(){editing=i;renderChat()};act.appendChild(eb)}if(m.role==="assistant"){if(collectCodeFromText(m.content).length){var zb=el("button","mini","\ud83d\udce6 ZIP");zb.onclick=function(){zipFromText(m.content,"ai-output")};act.appendChild(zb)}var __wp=collectCodeFromText(m.content).filter(function(c){return c.path});if(__wp.length){var gb=el("button","mini","\ud83d\ude80 Commit GitHub");gb.onclick=function(){var msg=prompt("Pesan commit:","Update "+__wp.length+" file via notionku");if(msg==null)return;ghCommit(__wp.map(function(c){return{path:c.path,content:c.text}}),msg)};act.appendChild(gb)}if(i===state.chat.length-1){var rb=el("button","mini","\ud83d\udd04 Ulangi");rb.onclick=function(){regenerateFrom(i)};act.appendChild(rb)}}body.appendChild(act);d.appendChild(body);th.appendChild(d)});c.appendChild(th);if(window.__autoStick)c.scrollTop=c.scrollHeight;updateScrollBtn()}
function buildContext(){var sys="Kamu asisten coding yang membantu. Balas dalam bahasa Indonesia kecuali diminta lain. Untuk kode, selalu pakai blok kode markdown dengan nama bahasa. Kalau kode untuk file tertentu, tulis nama path setelah bahasa di pembuka blok (mis. js src/app.js) biar bisa di-ZIP/commit rapi. Kalau user minta edit atau commit ke GitHub, tulis tiap file sebagai blok kode lengkap dengan path di pembuka blok; nanti user klik tombol Commit. Kalau mau kasih pilihan ke user, tulis di baris terpisah diawali ::OPTIONS:: lalu opsi dipisah tanda |. Kalau ada fakta penting jangka panjang tentang user/proyek, tulis di baris diawali ::MEMORY:: .";if(state.memory.length)sys+="\nMemori: "+state.memory.join("; ");var ctxPages=state.context.slice();if($("ctx").checked&&state.blocks.length&&!ctxPages.some(function(x){return x.id===state.current})){ctxPages.push({id:state.current,title:state.title,codes:collectCode()})}ctxPages.forEach(function(pg){if(pg.codes&&pg.codes.length){sys+="\n\nKode dari '"+pg.title+"':\n";pg.codes.forEach(function(c){sys+=FENCE+c.language+(c.path?(" "+c.path):"")+"\n"+c.text+"\n"+FENCE+"\n"})}});return sys}
function msgsForApi(){var arr=[{role:"system",content:buildContext()}];state.chat.forEach(function(m){var txt=m.content;var imgs=(m.files||[]).filter(function(f){return f.kind==="image"});(m.files||[]).forEach(function(f){if(f.kind==="text")txt+="\n\n[File: "+f.name+"]\n"+f.text});if(imgs.length){var parts=[{type:"text",text:txt}];imgs.forEach(function(f){parts.push({type:"image_url",image_url:{url:f.dataUrl}})});arr.push({role:m.role,content:parts})}else{arr.push({role:m.role,content:txt})}});return arr}
async function streamReply(){
var c=$("msgs");pushMsg("assistant","");var idx=state.chat.length-1;window.__autoStick=true;renderChat();
var ctrl=new AbortController();window.__ctrl=ctrl;$("send").textContent="\u25a0";
var baseMsgs=msgsForApi();var acc="";var rid="resume:"+(state.chatId||"new");var lastP=0;var cacheFlag=window.__nocacheOnce?false:true;window.__nocacheOnce=false;
function paint(){var bub=document.querySelectorAll(".msg.assistant .bubble");if(bub.length){var last=bub[bub.length-1];last.innerHTML=mdRender(stripMemory(acc).body)}if(window.__autoStick)c.scrollTop=c.scrollHeight;updateScrollBtn()}
function persist(force){var now=Date.now();if(!force&&now-lastP<600)return;lastP=now;try{localStorage.setItem(rid,JSON.stringify({idx:idx,acc:acc,t:now}))}catch(e){}}
function clearPersist(){try{localStorage.removeItem(rid)}catch(e){}}
async function once(msgs){
var res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:msgs,model:($("model").value||"").trim()||undefined,cache:cacheFlag}),signal:ctrl.signal});
if(!res.ok||!res.body){var er=await res.json().catch(function(){return{}});var e2=new Error(er.error||("HTTP "+res.status));e2.fatal=(res.status===400||res.status===401||res.status===403);throw e2}
var reader=res.body.getReader();var dec=new TextDecoder();var buf="";
while(true){var rd=await reader.read();if(rd.done)break;buf+=dec.decode(rd.value,{stream:true});var parts=buf.split("\n");buf=parts.pop();for(var k=0;k<parts.length;k++){var line=parts[k].trim();if(!line||line.indexOf("data:")!==0)continue;var payload=line.slice(5).trim();if(payload==="[DONE]")continue;try{var j=JSON.parse(payload);var delta=(j.choices&&j.choices[0]&&(j.choices[0].delta&&j.choices[0].delta.content))||j.response||"";if(delta){acc+=delta;state.chat[idx].content=acc;paint();persist(false)}}catch(e){}}}
}
var tries=0;var maxTries=4;
try{
while(true){
try{
var msgs=baseMsgs;
if(acc){msgs=baseMsgs.slice();if(msgs.length&&msgs[msgs.length-1].role==="assistant"){msgs[msgs.length-1]={role:"assistant",content:acc}}else{msgs.push({role:"assistant",content:acc})}msgs.push({role:"user",content:"Lanjutkan jawaban sebelumnya persis dari karakter terakhir yang kamu tulis. Jangan mengulang bagian yang sudah ada, langsung sambung."});cacheFlag=false}
await once(msgs);
break;
}catch(e){
if(e.name==="AbortError")throw e;
if(e.fatal)throw e;
tries++;
if(tries>=maxTries)throw e;
var wait=Math.min(700*Math.pow(2,tries-1),6000);
state.chat[idx].content=acc+"\n\n\u23f3 *Koneksi terputus, menyambung ulang ("+tries+"/"+(maxTries-1)+")...*";paint();
await new Promise(function(r){setTimeout(r,wait)});
if(window.__ctrl!==ctrl)throw new Error("Dibatalkan");
}
}
state.chat[idx].content=acc;
var facts=collectMemoryFrom(acc);if(facts.length){facts.forEach(function(f){if(state.memory.indexOf(f)<0)state.memory.push(f)});saveMemory()}
clearPersist();renderChat();
}catch(e){
if(e.name!=="AbortError"){
if(acc){state.chat[idx].content=acc+"\n\n\u26a0\ufe0f *Terputus: "+e.message+". Klik \u25b6\ufe0f Lanjutkan untuk menyambung.*";persist(true)}
else{state.chat[idx].content="\u26a0\ufe0f "+e.message}
toast("Error: "+e.message,true)
}else{clearPersist()}
renderChat()
}finally{window.__ctrl=null;$("send").textContent="\u2191";saveHistory()}
}
async function sendChat(){var inp=$("chatin");var text=inp.value.trim();if(!text&&!pending.length)return;if(window.__ctrl){return}if(isZipCmd(text)){pushMsg("user",text);pushMsg("assistant","Oke, aku bungkus semua kode jadi satu ZIP \ud83d\udce6");renderChat();zipAll();inp.value="";return}var files=pending.slice();pending=[];renderAttbar();pushMsg("user",text,files);inp.value="";inp.style.height="auto";window.__autoStick=true;renderChat();await streamReply()}
async function saveEdit(i,nt){state.chat[i].content=nt;state.chat=state.chat.slice(0,i+1);editing=-1;renderChat();await streamReply()}
async function regenerateFrom(i){window.__nocacheOnce=true;state.chat=state.chat.slice(0,i);renderChat();await streamReply()}
function newChat(){state.chat=[];state.chatId=null;history.pushState({},"","/");renderChat();loadHistory()}
async function openChat(id){if(!id){newChat();return}try{var r=await fetch("/api/history?id="+encodeURIComponent(id));var d=await r.json();if(d.error){toast(d.error,true);return}state.chatId=d.id;state.chat=d.messages||[];history.pushState({},"","/chat/"+encodeURIComponent(d.id));renderChat();renderHistory();if(window.innerWidth<=900){document.body.classList.add("nohist");updateBackdrop()}}catch(e){toast("Gagal buka chat",true)}}
async function saveHistory(){try{if(!state.chat.length)return;var payload={id:state.chatId,messages:state.chat};if(!state.chatId){var fu=state.chat.filter(function(m){return m.role==="user"})[0];payload.title=fu?fu.content.slice(0,60):"Chat baru"}var r=await fetch("/api/history/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});var d=await r.json();if(d.ok&&d.id){var isNew=state.chatId!==d.id;state.chatId=d.id;if(isNew)history.replaceState({},"","/chat/"+encodeURIComponent(d.id));loadHistory()}}catch(e){}}
async function loadHistory(){try{var r=await fetch("/api/history");var d=await r.json();__sessions=d.sessions||[];renderHistory()}catch(e){}}
function renderHistory(){var box=$("histlist");var f=($("histsearch").value||"").toLowerCase();box.innerHTML="";__sessions.filter(function(s){return !f||(s.title||"").toLowerCase().indexOf(f)>=0}).forEach(function(s){var it=el("div","hitem"+(state.chatId===s.id?" active":""));var t=el("div","t",esc(s.title));t.onclick=function(){openChat(s.id)};it.appendChild(t);var rn=el("button","a","\u270f\ufe0f");rn.onclick=function(ev){ev.stopPropagation();renameChat(s.id,s.title)};var dl=el("button","a","\ud83d\uddd1\ufe0f");dl.onclick=function(ev){ev.stopPropagation();delChatById(s.id)};it.appendChild(rn);it.appendChild(dl);box.appendChild(it)})}
async function renameChat(id,old){var t=prompt("Nama baru buat chat ini:",old||"");if(t==null)return;t=t.trim();if(!t)return;try{await fetch("/api/history/rename",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id,title:t})});toast("Nama chat diubah")}catch(e){toast("Gagal ganti nama",true)}loadHistory()}
async function delChatById(id){if(!confirm("Hapus chat ini?"))return;try{await fetch("/api/history/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id})})}catch(e){}if(state.chatId===id)newChat();else loadHistory()}
async function exportData(){toast("Menyiapkan export...");try{var r=await fetch("/api/history");var d=await r.json();var list=d.sessions||[];var sessions=[];for(var i=0;i<list.length;i++){var rs=await fetch("/api/history?id="+encodeURIComponent(list[i].id));var sj=await rs.json();if(!sj.error)sessions.push({id:sj.id,title:sj.title,messages:sj.messages})}var mem=[];try{mem=(await (await fetch("/api/memory")).json()).facts||[]}catch(e){}var blob=new Blob([JSON.stringify({version:1,exported:Date.now(),sessions:sessions,memory:mem},null,2)],{type:"application/json"});downloadFile("notionku-backup.json",blob);toast("Export selesai ("+sessions.length+" chat)")}catch(e){toast("Gagal export",true)}}
function importData(file){var reader=new FileReader();reader.onload=async function(){try{var d=JSON.parse(reader.result);var sessions=d.sessions||[];for(var i=0;i<sessions.length;i++){await fetch("/api/history/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:sessions[i].id,title:sessions[i].title,messages:sessions[i].messages})})}if(d.memory){await fetch("/api/memory/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({facts:d.memory})});state.memory=d.memory}toast("Import selesai ("+sessions.length+" chat)");loadHistory()}catch(e){toast("File backup nggak valid",true)}};reader.readAsText(file)}
async function loadGhTree(){if(window.innerWidth>900)document.body.classList.add("shownotion");$("page").innerHTML='<p class="muted">Memuat repo...</p>';try{var r=await fetch("/api/gh/tree");var d=await r.json();if(d.error){$("page").innerHTML='<p class="muted">'+esc(d.error)+'</p>';toast(d.error,true);return}var box=$("page");box.innerHTML='<div class="title">\ud83d\udcbb '+esc(d.repo)+' ('+esc(d.branch)+')</div>';if(!d.files.length){box.innerHTML+='<p class="muted">Repo kosong.</p>';return}var list=el("div","plist");d.files.forEach(function(f){var it=el("div","pitem","\ud83d\udcc4 "+esc(f.path));it.onclick=function(){openGhFile(f.path)};list.appendChild(it)});box.appendChild(list)}catch(e){toast("Gagal load repo",true)}}
async function openGhFile(path){$("page").innerHTML='<p class="muted">Memuat '+esc(path)+'...</p>';try{var r=await fetch("/api/gh/file?path="+encodeURIComponent(path));var d=await r.json();if(d.error){toast(d.error,true);return}renderGhFile(d)}catch(e){toast("Gagal buka file",true)}}
function renderGhFile(d){var box=$("page");box.innerHTML="";var bk=el("button","btn","\u2190 Daftar file");bk.onclick=loadGhTree;box.appendChild(bk);box.appendChild(el("div","title","\ud83d\udcc4 "+esc(d.path)));var card=el("div","codecard");var head=el("div","codehead");var sp=el("span","sp",esc(d.path));head.appendChild(sp);var ctxb=el("button","btn","\u2795 Konteks");var save=el("button","btn","\ud83d\udcbe Commit");head.appendChild(ctxb);head.appendChild(save);var ta=el("textarea");ta.value=d.content;card.appendChild(head);card.appendChild(ta);box.appendChild(card);save.onclick=function(){var msg=prompt("Pesan commit:","Update "+d.path+" via notionku");if(msg==null)return;ghCommit([{path:d.path,content:ta.value,sha:d.sha}],msg)};ctxb.onclick=function(){state.context=state.context.filter(function(x){return x.id!=="gh:"+d.path});state.context.push({id:"gh:"+d.path,title:d.path,codes:[{language:extFromPath(d.path),text:ta.value,path:d.path}]});renderCtxInfo();toast("Konteks + "+d.path)}}
async function ghCommit(files,msg){toast("Commit ke GitHub...");try{var r=await fetch("/api/gh/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({files:files,message:msg})});var d=await r.json();if(d.error){toast(d.error,true);return}var ok=(d.results||[]).filter(function(x){return x.ok}).length;var fail=(d.results||[]).length-ok;toast("Commit: "+ok+" sukses"+(fail?(", "+fail+" gagal"):""),fail>0);(d.results||[]).forEach(function(x){if(!x.ok)console.error("Commit gagal "+x.path+": "+x.error)})}catch(e){toast("Gagal commit",true)}}
async function ghConnect(){var stat=$("ghconnstat");var box=$("ghconnbox");var cid=$("setghclient").value.trim();if(!cid){box.textContent="Isi OAuth Client ID dulu.";return}stat.textContent="Menyimpan...";await fetch("/api/settings/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gh_client_id:cid})});stat.textContent="Menghubungkan...";var d;try{var r=await fetch("/api/gh/oauth/start",{method:"POST"});d=await r.json()}catch(e){stat.textContent="Gagal connect";return}if(d.error){stat.textContent="";box.textContent=d.error;return}box.innerHTML='Buka <a href="'+d.verification_uri+'" target="_blank">'+d.verification_uri+'</a> lalu masukin kode: <b style="font-size:16px;letter-spacing:2px">'+d.user_code+'</b>';stat.textContent="Nunggu otorisasi di GitHub...";var iv=(d.interval||5)*1000;var deadline=Date.now()+((d.expires_in||900)*1000);var poll=async function(){if(Date.now()>deadline){stat.textContent="Kadaluarsa, klik Connect lagi.";return}try{var pr=await fetch("/api/gh/oauth/poll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({device_code:d.device_code})});var pd=await pr.json();if(pd.ok){stat.textContent="Terhubung!";box.innerHTML="";toast("GitHub terhubung");ghLoadRepos();return}if(pd.error==="slow_down"){iv+=5000}if(pd.error&&pd.error!=="authorization_pending"&&pd.error!=="slow_down"){stat.textContent=pd.error;return}setTimeout(poll,iv)}catch(e){setTimeout(poll,iv)}};setTimeout(poll,iv)}
async function ghLoadRepos(){var sel=$("setghrepo2");if(!sel)return;try{var r=await fetch("/api/gh/repos");var d=await r.json();if(d.error){toast(d.error,true);return}sel.innerHTML="";var ph=document.createElement("option");ph.value="";ph.textContent="\u2014 pilih repository \u2014";sel.appendChild(ph);(d.repos||[]).forEach(function(x){var o=document.createElement("option");o.value=x.full_name+"::"+x.default_branch;o.textContent=x.full_name;if(x.full_name===d.current)o.selected=true;sel.appendChild(o)});sel.style.display="block"}catch(e){toast("Gagal ambil repo",true)}}
async function ghSelectRepo(val){if(!val)return;var parts=val.split("::");var fn=parts[0];var br=parts[1]||"main";var seg=fn.split("/");var owner=seg[0];var repo=seg.slice(1).join("/");await fetch("/api/settings/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gh_owner:owner,gh_repo:repo,gh_branch:br})});if($("setghowner"))$("setghowner").value=owner;if($("setghrepo"))$("setghrepo").value=repo;if($("setghbranch"))$("setghbranch").value=br;toast("Repo dipilih: "+fn)}
function openSettings(){fetch("/api/settings").then(function(r){return r.json()}).then(function(d){if(d.error){toast(d.error,true);return}$("settokens").value="";$("settokinfo").textContent=(d.tokens&&d.tokens.length)?("Tersimpan: "+d.tokens.join(", ")+". Isi ulang buat ganti."):"Belum ada token.";$("setkey").value="";$("setkey").placeholder=d.openai_key_set?"(tersimpan) isi buat ganti":"sk-...";$("setbase").value=d.openai_base||"";$("setmodel").value=d.openai_model||"";$("setai").value=d.ai_model||"";$("setgh").value="";$("setgh").placeholder=d.gh_token_set?"(tersimpan) isi buat ganti":"ghp_...";$("setghowner").value=d.gh_owner||"";$("setghrepo").value=d.gh_repo||"";$("setghbranch").value=d.gh_branch||"";$("setghclient").value=d.gh_client_id||"";if(d.gh_token_set){ghLoadRepos()}$("setmodal").style.display="flex"}).catch(function(){toast("Gagal load pengaturan",true)})}
function closeSettings(){$("setmodal").style.display="none"}
async function saveSettings(){var body={openai_base:$("setbase").value,openai_model:$("setmodel").value,ai_model:$("setai").value};var tk=$("settokens").value.trim();if(tk)body.tokens=tk.split("\n").map(function(x){return x.trim()}).filter(function(x){return x});var key=$("setkey").value.trim();if(key)body.openai_key=key;body.gh_owner=$("setghowner").value;body.gh_repo=$("setghrepo").value;body.gh_branch=$("setghbranch").value;var ght=$("setgh").value.trim();if(ght)body.gh_token=ght;$("setmsg").textContent="Menyimpan...";try{var r=await fetch("/api/settings/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});var d=await r.json();if(d.error){$("setmsg").textContent=d.error;return}$("setmsg").textContent="Tersimpan \u2713";toast("Pengaturan disimpan");loadAccounts().then(doSearch);loadModels();setTimeout(closeSettings,700)}catch(e){$("setmsg").textContent="Gagal simpan"}}
function routeFromUrl(){var m=location.pathname.match(/^\/chat\/(.+)$/);if(m){var id=decodeURIComponent(m[1]);fetch("/api/history?id="+encodeURIComponent(id)).then(function(r){return r.json()}).then(function(d){if(d&&!d.error){state.chatId=d.id;state.chat=d.messages||[];renderChat();renderHistory()}})}}
$("togghist").onclick=function(){document.body.classList.toggle("nohist");updateBackdrop()};
$("toggnotion").onclick=function(){document.body.classList.toggle("shownotion");updateBackdrop()};
$("closenotion").onclick=function(){document.body.classList.remove("shownotion");updateBackdrop()};
$("backdrop").onclick=function(){document.body.classList.add("nohist");document.body.classList.remove("shownotion");updateBackdrop()};
$("settings").onclick=openSettings;$("setclose").onclick=closeSettings;$("setsave").onclick=saveSettings;
$("setmodal").addEventListener("click",function(e){if(e.target===this)closeSettings()});
$("setexport").onclick=exportData;$("setimport").onclick=function(){$("impfile").click()};
$("impfile").addEventListener("change",function(){if(this.files&&this.files[0])importData(this.files[0]);this.value=""});
$("theme").onclick=toggleTheme;$("membtn").onclick=showMemory;$("newchat").onclick=newChat;
$("histsearch").addEventListener("input",renderHistory);
$("search").addEventListener("input",function(){clearTimeout(window.__st);window.__st=setTimeout(doSearch,300)});
$("acc").addEventListener("change",doSearch);
$("turbo").addEventListener("change",function(){if(state.current)openPage(state.current);else doSearch()});
$("refresh").onclick=function(){if(state.current)openPage(state.current);else doSearch()};
$("addctx").onclick=addContext;$("ctxinfo").onclick=function(){if(state.context.length)clearContext()};$("ctx").addEventListener("change",renderCtxInfo);
$("ghbtn").onclick=loadGhTree;$("ghconnect").onclick=ghConnect;$("setghrepo2").onchange=function(){ghSelectRepo(this.value)};
$("zip").onclick=exportZip;$("addcode").onclick=addCode;$("pinbtn").onclick=togglePin;
$("find").addEventListener("input",function(){var v=this.value.trim();clearTimeout(window.__ft);window.__ft=setTimeout(function(){findInPage(v)},250)});
$("send").onclick=function(){if(window.__ctrl){window.__ctrl.abort()}else{sendChat()}};
$("chatin").addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendChat()}});
$("chatin").addEventListener("input",function(){this.style.height="auto";this.style.height=Math.min(this.scrollHeight,200)+"px"});
$("attach").onclick=function(){$("fileinput").click()};
$("fileinput").addEventListener("change",function(){if(this.files&&this.files.length)addFiles(this.files);this.value=""});
$("chatin").addEventListener("paste",function(e){var items=(e.clipboardData||{}).items||[];var fs=[];for(var i=0;i<items.length;i++){if(items[i].kind==="file"){var f=items[i].getAsFile();if(f)fs.push(f)}}if(fs.length){e.preventDefault();addFiles(fs)}});
$("msgs").addEventListener("click",function(e){var b=e.target&&e.target.closest?e.target.closest(".codetoggle"):null;if(!b)return;var w=b.closest(".codewrap");if(!w)return;var col=w.classList.toggle("collapsed");b.textContent=col?"Lebarkan":"Kecilkan"});
$("msgs").addEventListener("scroll",function(){window.__autoStick=nearBottom();updateScrollBtn()});
$("scrollbtn").onclick=function(){window.__autoStick=true;var c=$("msgs");c.scrollTop=c.scrollHeight;updateScrollBtn()};
window.__autoStick=true;applyTheme();renderPins();renderCtxInfo();
if(window.innerWidth<=900)document.body.classList.add("nohist");
updateBackdrop();
loadAccounts().then(doSearch);
loadModels();loadHistory();loadMemory();renderChat();updateScrollBtn();routeFromUrl();
window.addEventListener("resize",updateBackdrop);
window.addEventListener("popstate",routeFromUrl);
}
export const CLIENT_JS = (function(){var s=__clientMain.toString();return s.slice(s.indexOf("{")+1,s.lastIndexOf("}"));})();
